version: '2'

# Start all machines
services:
    mochi:
        container_name: mochi
        build: mochi
        ports:
            - 7417:8080
    hoo:
        container_name: hoo
        build: hoo
        ports:
            - 7418:8080
    qilin:
        container_name: qilin
        build: qilin
        ports:
            - 7419:8080
    nue:
        container_name: nue
        build: nue
        ports:
            - 7420:8080