version: '2'

# Start all machines
services:
    dosei:
        container_name: dosei
        build: dosei
        ports:
            - 5432:5432
        volumes:
            - gumi:/home/dosei
        environment:
        - POSTGRES_PASSWORD=S3cret
        - POSTGRES_USER=citizix_user
    mochi:
        container_name: mochi
        build: mochi
        ports:
            - 7417:8080
    hoo:
        container_name: hoo
        build: hoo
        ports:
            - 7418:8080
    qilin:
        container_name: qilin
        build: qilin
        ports:
            - 7419:8080
    nue:
        container_name: nue
        build: nue
        ports:
            - 7420:8080


volumes:
  gumi: